### ISSUE TITLE
Error after installing in HACS (version v0.1.0 of ad-batterycheck)

### ISSUE THREAD

**Issue by fredamn76** [benleb/ad-batterycheck#1]
`2019-08-05 18:04:09.576798 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2019-08-05 18:04:09.576883 INFO AppDaemon: App 'batterycheck' added
2019-08-05 18:04:09.576956 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2019-08-05 18:04:09.577034 INFO AppDaemon: Adding /config/appdaemon/apps/batterycheck to module import path
2019-08-05 18:04:09.577206 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2019-08-05 18:04:09.577277 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/batterycheck/batterycheck.py
2019-08-05 18:04:09.578017 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 18:04:09.578109 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/batterycheck/batterycheck.py:
2019-08-05 18:04:09.578154 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 18:04:09.579959 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/batterycheck/batterycheck.py", line 17, in <module>
    import adutils
ModuleNotFoundError: No module named 'adutils'
2019-08-05 18:04:09.580095 WARNING AppDaemon: Removing associated apps:
2019-08-05 18:04:09.580142 WARNING AppDaemon: batterycheck
2019-08-05 18:04:09.580046 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 18:04:09.580542 INFO AppDaemon: App initialization complete`

**Comment by benleb** [comment]
fixed via #04af0fa and v0.1.1 released, please try this.

But you will have to restart your appdaemon after installation as appdaemon just checks for required packages on start. I am already investigating how this could be simplified...

**Comment by fredamn76** [comment]
I updated to 0.1.1 but still get this error. I also restarted appdaemon.

`2019-08-05 20:19:01.638441 INFO AppDaemon: App 'batterycheck' added
2019-08-05 20:19:01.638558 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2019-08-05 20:19:01.638742 INFO AppDaemon: Adding /config/appdaemon/apps/batterycheck to module import path
2019-08-05 20:19:01.638979 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/hello.py - ignoring
2019-08-05 20:19:01.639061 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/batterycheck/batterycheck.py
2019-08-05 20:19:01.656775 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 20:19:01.656943 WARNING AppDaemon: Unexpected error loading module: /config/appdaemon/apps/batterycheck/batterycheck.py:
2019-08-05 20:19:01.657024 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 20:19:01.664992 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 2026, in check_app_updates
    self.read_app(mod["name"], mod["reload"])
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1809, in read_app
    self.modules[module_name] = importlib.import_module(module_name)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/appdaemon/apps/batterycheck/batterycheck.py", line 17, in <module>
    import adutils
ModuleNotFoundError: No module named 'adutils'
2019-08-05 20:19:01.665082 WARNING AppDaemon: ------------------------------------------------------------
2019-08-05 20:19:01.665171 WARNING AppDaemon: Removing associated apps:
2019-08-05 20:19:01.665230 WARNING AppDaemon: batterycheck
2019-08-05 20:19:01.665612 INFO AppDaemon: App initialization complete`

**Comment by benleb** [comment]
There should be something like this in your AppDaemon log, isnt it? :D Or some hint why it wont install it?
```
...
Collecting adutils==0.1.0 (from -r /conf/apps/batterycheck/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/d2/e1/c242df48cc2cda7fb05096a8ab9bc27928bf183a2f7759f6c725a44b13f4/adutils-0.1.0-py3-none-any.whl
Installing collected packages: adutils
Successfully installed adutils-0.1.0
...
```

I will try to reproduce this, which Home Assistant, HACS and AppDaemon version do you run?

**Comment by fredamn76** [comment]
I run Hassio addon of Appdaemon version 4.0.1. Mer info att https://github.com/hassio-addons/addon-appdaemon3.

Where can i find the logfile you requested? The "log" i have posted is from the Hassio addon.

**Comment by thundergreen** [comment]
I got it installed but get this error:

```
2019-08-16 14:20:33.841048 WARNING AppDaemon: ------------------------------------------------------------
2019-08-16 14:20:33.841345 WARNING AppDaemon: Unexpected error running initialize() for batterycheck
2019-08-16 14:20:33.841523 WARNING AppDaemon: ------------------------------------------------------------
2019-08-16 14:20:33.841945 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 1581, in init_object
    init()
  File "/config/appdaemon/apps/batterycheck/batterycheck.py", line 44, in initialize
    adutils.show_info(self.log, APP_NAME, self.cfg, list(), icon=APP_ICON)
  File "/usr/lib/python3.7/site-packages/adutils/__init__.py", line 28, in show_info
    log(app_name, ascii_encode=ascii_encode)  # type: ignore
TypeError: log() got an unexpected keyword argument 'ascii_encode'
```

**Comment by evildad** [comment]
You have to use a newer Version of appdaemon to get rid of this error....

This is the cause of it.
https://github.com/home-assistant/appdaemon/pull/417

**Comment by thundergreen** [comment]
The problem is i am using hassio. Could someone merge this please ?

**Comment by benleb** [comment]
The app needs the current 4.0 beta (or master/dev branch) of appdaemon, sorry. I made this clear in the readme now.
